imdb_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: {{ env_var('GCP_PROJECT_ID') }}
      dataset: {{ env_var('BIGQUERY_DATASET') }}
      threads: 4 # Must be a value of 1 or greater
      keyfile: {{ env_var('GCP_CREDENTIALS') }} 
      OPTIONAL_CONFIG: VALUE